
# Colors (Hyper)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.cursor]
text = '#ffffff'
cursor = '#00cc00'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ff0000'
green   = '#002200'
yellow  = '#ffff00'
blue    = '#00ff00'
magenta = '#00aa00'
cyan    = '#00ff00'
white   = '#ffff00'

# Bright colors
[colors.bright]
black   = '#000000'
red     = '#ff0000'
green   = '#002200'
yellow  = '#ffff00'
blue    = '#00ff00'
magenta = '#00aa00'
cyan    = '#00ff00'
white   = '#ffff00'

[window]
opacity = 0.8
decorations = "full"
